### ISSUE TITLE
Add link to this repo in the ostis-monography repo README

### ISSUE THREAD

**Issue by AlexandrZagorskiy** [SHtress/check_monography_script#3]
We can forget about this scripts, but they can be useful. Leave a link, I don't think that this version of monography will be the last

**Comment by SHtress** [comment]
Don't worry i will try to collect all useful automation tools here and add link to this repo in monography.

**Comment by SHtress** [comment]
Fixed [here](https://github.com/ostis-ai/monography2022/pull/365).
